### PR TITLE
Note Taking app

### PR DESCRIPTION
**Pull request by alibardide5124**
# Description

Made a note-taking app, as it was said in issue #8. Contributing for Hacktoberfest :) and I used room database, hilt and Compose Destinations libraries for this project

## Issue
Issue #8 

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Do not use dash in name of folder

**Comment by alibardide5124** [comment]
Hi @prodigyinfotech!
I made the necessary changes. Could you please review this pull request?

**Comment by prodigyinfotech** [comment]
Add more screenshots of the app in readme file.

**Comment by alibardide5124** [comment]
Hi @prodigyinfotech!
I've added screenshots as you asked :)

**Pull request merged**
