### PR TITLE
Add expense_tracker

### LINKED ISSUE #6: Budget Tracker
Build a budget tracking app that helps users manage their expenses by allowing users to input income and expenses.

### PR DESCRIPTION
**Pull request by iPriyanshu19**
# Description

**Expense Tracker App**
An intuitive Expense Tracker application built using Flutter, designed to help users manage their daily expenses efficiently. This app features a beautiful user interface, smooth animations, and a simple way to track income and expenses.

**Features**
- Add, update, and delete expense or income entries.
- View expenses in a categorized and date-wise manner.
- Graphical representation of spending habits using pie and bar charts.
- Swipe to delete or edit entries.
- Persistent storage using the Isar NoSQL database.
- Multi-platform support: Android and iOS.

## Issue
Fixes #6 

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by iPriyanshu19** [comment]
Please add Hacktoberfest labels.
@prodigyinfotech

**Comment by prodigyinfotech** [comment]
the submodule is not working. Can you re-check it

**Comment by iPriyanshu19** [comment]
Download Flutter sdk from its site first. Then,
1. Open the module
2. Run `flutter pub get`
3. Then navigate to *main.dart* file in lib folder and press *Run without debugging* after connecting a physical device or android emulator.
Below is the screenshot attached of working of the module:-
image

**Comment by prodigyinfotech** [comment]
Check href of Submodule. It doesnt seem to work

**Pull request closed without merging**
