### PR TITLE
MVVM Architectured TODO List

### PR DESCRIPTION
**Pull request by Pranishkafle6175**
# Description

This is a MVVM Architectured Based TODO List. The TO-DO list app is efficiently designed and structured using MVVM
architecture, ensuring a clear separation of Ui and the business logic. It Efficiently manages tasks with features like saving, updating, and deleting.

## Issue

Fixes # 2(issue)

## Type of change
- [x] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Please include a README file and rename the project folder to something better

**Comment by Pranishkafle6175** [comment]
Ok, I will do that.

**Comment by Pranishkafle6175** [comment]
Hello,
Can i put some detail and linkedlin link of mine at the end of the readme
of my application!

**Comment by prodigyinfotech** [comment]
Yes

**Comment by prodigyinfotech** [comment]
Hey @Pranishkafle6175,
Since it might be difficult for everyone to compile and check the app, please include some screenshots of the app.

**Pull request merged**
